markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

name: "某校某院某级某班博文录"
author: "我们"

permalink: /:year/:month/:day/:title.html

navigations:
  - title: Archive
    name: ARCHIVE
    href: /archive.html
  - title: Tags
    name: TAGS
    href: /tags.html
  - title: About
    name: ABOUT
    href: /about.html

comments:
  provider: duoshuo
  duoshuo:
    short_name: pkuphys
